fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--check", "--skip-string-normalization"] # trunk-ignore(yamllint/quoted-strings)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint .
        language: system
        types: [python]